version: 0.2
phases:
  install:
    runtime-versions:
      java: java-21-openjdk-amd64
  pre_build:
    commands:
      - echo Initializing build environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 211125690527 --query authorizationToken --output text`
  build:
    commands:
      - echo "Build started on `date`"
      - mvn -s settings.xml package
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - 'target/nextwork-web-project.war'
  discard-paths: no